### ISSUE TITLE
Decide on standard configuration for Python

### ISSUE THREAD

**Issue by klauer** [pcdshub/pre-commit-hooks#1]
Current test one is:

```sh
$ cat .pre-commit-config.yaml
```
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
```

Add:

- [x] Import sorting via `isort`?
